### ISSUE TITLE
same name issue

### ISSUE THREAD

**Issue by Moose378** [samjesus8/DokkanPassiveGenerator#1]
If two passives with the same name are made, it makes the entire thing stop working, and an error pops up when trying to Use or Manage Passives.

![Screenshot_20221223_102835](https://user-images.githubusercontent.com/121330375/209422886-0089a6ff-edbe-4c1b-9beb-d0bd8c0b327b.png)

**Comment by samjesus8** [comment]
Alright so for now to eliminate this issue you need to delete the folder named "Passive Generator Files" in your My Documents and restart the application, it'll recreate the folder.

I will fix this issue as soon as I can. I appreciate the submission

**Comment by samjesus8** [comment]
I have addressed this issue in the latest update so please download and install the new version to implement this change. Thank you very much for the feedback

[V1.0.1 Download](https://github.com/samjesus8/DokkanPassiveGenerator/releases/tag/V1.0.1)
